version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"         
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/mernDB
      - STRIPE_SECRET_KEY=your_stripe_key
      - JWT_SECRET=your_jwt_secret
      - REFRESH_SECRET=your_refresh_secret
      - CLOUDINARY_API_KEY=your_cloudinary_api_key
      - CLOUDINARY_API_SECRET=your_cloudinary_api_secret
    depends_on:
      - mongo
      - flood-api

  flood-api:
    build: ./flood-prediction-api
    restart: always
    ports:
      - "5001:5001"           
    environment: {}
     
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"

volumes:
  mongo-data:
